# Generated by Django 3.2.20 on 2023-08-02 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0003_alter_booking_no_of_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='BookingDate',
            field=models.DateTimeField(default=datetime.date(2023, 8, 2)),
        ),
    ]
